"""Report generator — HTML, PDF, JSON, Markdown formats."""

import json
import os
from datetime import datetime
from pathlib import Path
from jinja2 import Template


HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>AutoRecon Report — {{ domain }}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Courier New', monospace; background: #0a0e14; color: #33ff88; padding: 2rem; }
  h1 { color: #00ff6a; font-size: 1.5rem; margin-bottom: 1rem; border-bottom: 1px solid #1a3a2a; padding-bottom: 0.5rem; }
  h2 { color: #00ff6a; font-size: 1.1rem; margin: 1.5rem 0 0.5rem; }
  h3 { color: #ffaa00; font-size: 0.9rem; margin: 1rem 0 0.3rem; }
  .meta { color: #667; font-size: 0.8rem; margin-bottom: 1rem; }
  table { width: 100%; border-collapse: collapse; margin: 0.5rem 0 1rem; font-size: 0.8rem; }
  th { background: #111820; color: #33ff88; text-align: left; padding: 0.4rem 0.6rem; border: 1px solid #1a3a2a; }
  td { padding: 0.4rem 0.6rem; border: 1px solid #1a3a2a; color: #b0d0c0; }
  .severity-critical { color: #ff3344; font-weight: bold; }
  .severity-high { color: #ff6633; font-weight: bold; }
  .severity-medium { color: #ffaa00; }
  .severity-low { color: #3388ff; }
  .summary-card { display: inline-block; background: #111820; padding: 1rem; margin: 0.5rem; border: 1px solid #1a3a2a; border-radius: 4px; min-width: 120px; text-align: center; }
  .summary-card .number { font-size: 1.5rem; color: #00ff6a; }
  .summary-card .label { font-size: 0.7rem; color: #667; }
  .executive { background: #111820; padding: 1rem; border-left: 3px solid #00ff6a; margin: 1rem 0; }
</style>
</head>
<body>
<h1>🔍 AutoRecon Report</h1>
<div class="meta">Target: {{ domain }} | Generated: {{ generated_at }} | Duration: {{ duration }}</div>

<div class="executive">
<h3>Executive Summary</h3>
<p>Automated reconnaissance scan of <strong>{{ domain }}</strong> identified {{ vulns | length }} vulnerabilities
({{ critical_count }} critical, {{ high_count }} high), {{ subdomains | length }} subdomains, and {{ ports | length }} open ports.</p>
</div>

<div>
  <div class="summary-card"><div class="number">{{ subdomains | length }}</div><div class="label">Subdomains</div></div>
  <div class="summary-card"><div class="number">{{ ports | length }}</div><div class="label">Open Ports</div></div>
  <div class="summary-card"><div class="number">{{ vulns | length }}</div><div class="label">Vulnerabilities</div></div>
  <div class="summary-card"><div class="number">{{ dirs | length }}</div><div class="label">Directories</div></div>
</div>

<h2>Vulnerabilities</h2>
<table>
<tr><th>Severity</th><th>CVE</th><th>Title</th><th>URL</th><th>Remediation</th></tr>
{% for v in vulns %}
<tr>
  <td class="severity-{{ v.severity }}">{{ v.severity | upper }}</td>
  <td>{{ v.cveId or 'N/A' }}</td>
  <td>{{ v.title }}</td>
  <td>{{ v.url }}</td>
  <td>{{ v.remediation }}</td>
</tr>
{% endfor %}
</table>

<h2>Subdomains</h2>
<table>
<tr><th>Subdomain</th><th>IP</th><th>Status</th><th>Title</th><th>Technologies</th></tr>
{% for s in subdomains %}
<tr><td>{{ s.subdomain }}</td><td>{{ s.ip }}</td><td>{{ s.statusCode }}</td><td>{{ s.title }}</td><td>{{ s.techStack | join(', ') }}</td></tr>
{% endfor %}
</table>

<h2>Open Ports</h2>
<table>
<tr><th>Port</th><th>Protocol</th><th>Service</th><th>Version</th><th>Risk</th></tr>
{% for p in ports %}
<tr><td>{{ p.port }}</td><td>{{ p.protocol }}</td><td>{{ p.service }}</td><td>{{ p.version }}</td><td class="severity-{{ p.risk }}">{{ p.risk | upper }}</td></tr>
{% endfor %}
</table>

<h2>Directories</h2>
<table>
<tr><th>Path</th><th>Status</th><th>Size</th><th>Interesting</th></tr>
{% for d in dirs %}
<tr><td>{{ d.path }}</td><td>{{ d.statusCode }}</td><td>{{ d.size }}</td><td>{{ '⚠️' if d.interesting else '' }}</td></tr>
{% endfor %}
</table>

<h2>Technologies</h2>
<table>
<tr><th>Name</th><th>Category</th><th>Version</th><th>Outdated</th></tr>
{% for t in techs %}
<tr><td>{{ t.name }}</td><td>{{ t.category }}</td><td>{{ t.version or 'N/A' }}</td><td>{{ '⚠️' if t.outdated else '✓' }}</td></tr>
{% endfor %}
</table>

<footer style="margin-top:2rem; color:#334; font-size:0.7rem; border-top:1px solid #1a3a2a; padding-top:0.5rem;">
Generated by AutoRecon v2.0 — For authorized use only
</footer>
</body>
</html>
"""


def generate_html(scan_data: dict) -> str:
    findings = scan_data.get("results", {})
    vulns = findings.get("vulnerabilities", [])
    template = Template(HTML_TEMPLATE)
    return template.render(
        domain=scan_data.get("domain", "unknown"),
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        duration=_calc_duration(scan_data),
        subdomains=findings.get("subdomains", []),
        ports=findings.get("ports", []),
        vulns=vulns,
        dirs=findings.get("directories", []),
        techs=findings.get("technologies", []),
        critical_count=sum(1 for v in vulns if v.get("severity") == "critical"),
        high_count=sum(1 for v in vulns if v.get("severity") == "high"),
    )


def generate_pdf(scan_data: dict) -> bytes:
    """Generate PDF using WeasyPrint from the HTML report."""
    from weasyprint import HTML as WHTML
    html_content = generate_html(scan_data)
    return WHTML(string=html_content).write_pdf()


def generate_json(scan_data: dict) -> str:
    return json.dumps(scan_data, indent=2, default=str)


def generate_markdown(scan_data: dict) -> str:
    findings = scan_data.get("results", {})
    vulns = findings.get("vulnerabilities", [])
    subs = findings.get("subdomains", [])
    ports = findings.get("ports", [])

    lines = [
        f"# AutoRecon Report — {scan_data.get('domain', 'unknown')}",
        f"**Date:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        f"**Duration:** {_calc_duration(scan_data)}",
        "",
        "## Executive Summary",
        f"Scan identified **{len(vulns)} vulnerabilities**, **{len(subs)} subdomains**, and **{len(ports)} open ports**.",
        "",
        "## Vulnerabilities",
        "| Severity | CVE | Title | URL |",
        "|----------|-----|-------|-----|",
    ]
    for v in vulns:
        lines.append(f"| {v['severity'].upper()} | {v.get('cveId', 'N/A')} | {v['title']} | {v['url']} |")

    lines += ["", "## Subdomains", "| Subdomain | Status | Title |", "|-----------|--------|-------|"]
    for s in subs:
        lines.append(f"| {s['subdomain']} | {s['statusCode']} | {s['title']} |")

    lines += ["", "## Open Ports", "| Port | Service | Version | Risk |", "|------|---------|---------|------|"]
    for p in ports:
        lines.append(f"| {p['port']} | {p['service']} | {p['version']} | {p['risk'].upper()} |")

    lines += ["", "---", "*Generated by AutoRecon v2.0 — For authorized use only*"]
    return "\n".join(lines)


def _calc_duration(scan_data: dict) -> str:
    started = scan_data.get("started_at", "")
    completed = scan_data.get("completed_at", "")
    if started and completed:
        try:
            s = datetime.fromisoformat(started)
            e = datetime.fromisoformat(completed)
            delta = e - s
            mins = int(delta.total_seconds() // 60)
            secs = int(delta.total_seconds() % 60)
            return f"{mins}m {secs}s"
        except Exception:
            pass
    return "N/A"
