import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { FileText, Download, Loader2 } from "lucide-react";
import { ScanResult } from "@/types/scan";

interface ReportGeneratorProps {
  result: ScanResult;
}

export function ReportGenerator({ result }: ReportGeneratorProps) {
  const [format, setFormat] = useState("html");
  const [generating, setGenerating] = useState(false);

  const generate = async () => {
    setGenerating(true);
    try {
      const res = await fetch("http://localhost:8000/api/report/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ scan_id: result.id, format }),
      });

      if (res.ok) {
        const blob = await res.blob();
        const ext = format === "markdown" ? "md" : format;
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `autorecon_${result.domain}.${ext}`;
        a.click();
        URL.revokeObjectURL(url);
      }
    } catch {
      // If backend unavailable, generate client-side markdown
      const md = generateClientMarkdown(result);
      const blob = new Blob([md], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `autorecon_${result.domain}.md`;
      a.click();
      URL.revokeObjectURL(url);
    }
    setGenerating(false);
  };

  return (
    <div className="flex items-center gap-2">
      <Select value={format} onValueChange={setFormat}>
        <SelectTrigger className="w-28 h-8 font-mono text-[10px] bg-secondary border-border">
          <SelectValue />
        </SelectTrigger>
        <SelectContent className="bg-card border-border">
          <SelectItem value="html" className="font-mono text-xs">HTML</SelectItem>
          <SelectItem value="pdf" className="font-mono text-xs">PDF</SelectItem>
          <SelectItem value="json" className="font-mono text-xs">JSON</SelectItem>
          <SelectItem value="markdown" className="font-mono text-xs">Markdown</SelectItem>
        </SelectContent>
      </Select>
      <Button
        onClick={generate}
        disabled={generating}
        size="sm"
        className="h-8 font-mono text-[10px] bg-primary text-primary-foreground hover:bg-primary/90"
      >
        {generating ? <Loader2 className="h-3 w-3 mr-1 animate-spin" /> : <Download className="h-3 w-3 mr-1" />}
        Report
      </Button>
    </div>
  );
}

function generateClientMarkdown(result: ScanResult): string {
  const f = result.findings;
  const lines = [
    `# AutoRecon Report — ${result.domain}`,
    `**Date:** ${new Date().toISOString()}`,
    "",
    "## Executive Summary",
    `Found **${f.vulnerabilities.length} vulnerabilities**, **${f.subdomains.length} subdomains**, **${f.ports.length} open ports**.`,
    "",
    "## Vulnerabilities",
    "| Severity | CVE | Title | URL |",
    "|----------|-----|-------|-----|",
    ...f.vulnerabilities.map(v => `| ${v.severity.toUpperCase()} | ${v.cveId || "N/A"} | ${v.title} | ${v.url} |`),
    "",
    "## Subdomains",
    "| Subdomain | Status | Title |",
    "|-----------|--------|-------|",
    ...f.subdomains.map(s => `| ${s.subdomain} | ${s.statusCode} | ${s.title} |`),
    "",
    "## Open Ports",
    "| Port | Service | Version | Risk |",
    "|------|---------|---------|------|",
    ...f.ports.map(p => `| ${p.port} | ${p.service} | ${p.version} | ${p.risk.toUpperCase()} |`),
    "",
    "---",
    "*Generated by AutoRecon v2.0*",
  ];
  return lines.join("\n");
}
